In [4]:
# Joining the numpy array - here for this we will pass concatenate()

import numpy  as np
ak = np.array([1,2,3])
ak1 =np.array([4,5,6])
ak3 = np.concatenate((ak1,ak))
ak2 = np.concatenate((ak,ak1))
print(ak2)
print(ak3)

[1 2 3 4 5 6]
[4 5 6 1 2 3]


In [6]:
# Joining of 2-D rray along with rows(axis = 1)
import numpy as np
ak = np.array([[1,2],[3,4]])
ak1 = np.array([[5,6],[7,8]])
ak3 = np.concatenate((ak,ak1),axis=1)
print(ak3)

[[1 2 5 6]
 [3 4 7 8]]


In [7]:
# Joining array using the stack function:
import numpy as np
ak = np.array([1,2,3])
ak1 = np.array([4,5,6])
ak3 = np.stack((ak,ak1),axis=1)
print(ak3)

[[1 4]
 [2 5]
 [3 6]]


In [9]:
# Stacking along with rows: hstack()
import numpy as np
ak = np.array([1,2,3])
ak1 = np.array([4,5,6])
ak3 = np.hstack((ak,ak1))
print(ak3)

[1 2 3 4 5 6]


In [10]:
# Stacking along with column
import numpy as np
ak = np.array([1,2,3])
ak1 = np.array([4,5,6])
ak3 = np.vstack((ak,ak1))
print(ak3)

[[1 2 3]
 [4 5 6]]


In [12]:
# stacking along with height(depth)
import numpy as np
ak = np.array([1,2,3])
ak1 = np.array([4,5,6])
ak3 = np.dstack((ak,ak1))
print(ak3)

[[[1 4]
  [2 5]
  [3 6]]]
