In [1]:
# searching array - you can search an array for a certain value and return the indexes that get the match. by using where()

import numpy as np
ak = np.array([1,2,3,4,5,4,4])
ak1 = np.where(ak==4)
print(ak1)

(array([3, 5, 6], dtype=int64),)


In [3]:
# Now we will find the indexes where the values are even:
import numpy as np
ak = np.array([1,2,3,4,5,6,7,8])
ak1 = np.where(ak%2 == 0)
print(ak1)

(array([1, 3, 5, 7], dtype=int64),)


In [4]:
#Now we will find  the indexes where the values are odd:
import numpy as np
ak = np.array([1,2,3,4,5,6,7,8])
ak1 = np.where(ak%2 == 1)
print(ak1)

(array([0, 2, 4, 6], dtype=int64),)


In [5]:
# Searchsorted() - perform binary search in array.
# we will now finf the index wher the value 7 should be insterted.

import numpy as np
ak = np.array([6,7,8,9])
ak1 = np.searchsorted(ak,7)
print(ak1)

1


In [6]:
# now we will search from right side
import numpy as np
ak = np.array([6,7,8,9])
ak1 = np.searchsorted(ak,7, side='right')
print(ak1)

2


In [7]:
# How to search multiple values:
import numpy as np
ak = np.array([1,3,5,7])
ak1 = np.searchsorted(ak,[2,4,6])
print(ak1)

[1 2 3]
