In [1]:
#Sort() the numpy ndarray object has a function which is called sort(),
# and this will sort a specified array.

import  numpy as np
ak =np.array([3,2,0,1])
print(np.sort(ak))

[0 1 2 3]


In [2]:
# sort the array alphabetically
import numpy as np
ak = np.array(['banana','cheery','apple'])
print(np.sort(ak))

['apple' 'banana' 'cheery']


In [3]:
# sort the boolean array:
import numpy as np
ak = np.array([True,False,True])
print(np.sort(ak))

[False  True  True]


In [4]:
# sorting the 2-D
import numpy as np
ak = np.array([[3,2,4],[5,0,1]])
print(np.sort(ak))

[[2 3 4]
 [0 1 5]]
