In [4]:
# Randam meaning - something that cannot be predicted logically.
# Now we will generate a random number from 0 to 100


# import numpy as np
from numpy import random
ak = random.randint(100)
print(ak)

56


In [6]:
# you can also generate float() via rand() from 0 to 1

from numpy import random
ak = random.rand()
print(ak)


0.08758345052633865


In [10]:
# you can also generate random Array.
# will will generate a 1-D array containing 5 random int from 0 to 100.

from numpy import random
ak = random.randint(100, size=(5))
print(ak)

[82 92 48 73 89]


In [15]:
# you can also generate random Array.
# will will generate a 2-D array with 3 rows,each row containing 5 random int from 0 to 100.

from numpy import random
ak = random.randint(100, size=(3,5))
print(ak)

[[98 69 15 75 72]
 [20 52 95 22 32]
 [30 87 54 77 92]]


In [16]:
# you can also generate random Array.
# will will generate a 1-D array containing 5 random float.

from numpy import random
ak = random.rand(5)
print(ak)

[0.4977891  0.14374126 0.47407705 0.81775588 0.95679873]


In [18]:
# you can also generate random Array.
# will will generate a 2-D array with 3 rows,each containing 5 random float.

from numpy import random
ak = random.rand(3,5)
print(ak)

[[0.1271468  0.82897979 0.39554157 0.15734882 0.75962246]
 [0.26638577 0.01087338 0.65789955 0.37718184 0.87391814]
 [0.32508741 0.63244504 0.00128965 0.09232296 0.7641127 ]]


In [45]:
# You can also generate random numbers from an array choice()
from numpy import random
ak = random.choice([2,4,6,8,7,9,4,2,1,3])
print(ak)


2


In [49]:
# You can also generate random numbers from an 2-D array choice()
from numpy import random
ak = random.choice([2,4,6,8,7,9,4,2,1,3],size=(3,5))
print(ak)

[[2 9 8 1 1]
 [9 4 7 6 2]
 [8 4 6 3 9]]
