In [3]:
# data distribution a list of all possible value and how often each vlue occor.

# such lists are important when working with statistics and data science.

#Random distribution : probability function.

# now we will generate 1-D with 100 values where  each value has to be 3,5,6,9

# the probabilty for the value 3 is set to be 0.1
# the probabilty for the value 5 is set to be 0.3
# the probabilty for the value 7 is set to be 0.6
# the probabilty for the value 9 is set to be 0.0

from numpy import random
ak = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0],size=(100))
print(ak)

[7 7 5 3 5 7 5 7 7 7 5 7 7 7 7 7 5 3 7 7 5 5 7 5 7 5 7 3 7 3 5 7 7 5 7 3 7
 7 7 7 7 5 7 5 7 5 7 7 7 3 5 3 7 7 7 7 7 5 3 7 5 7 7 5 7 7 5 3 3 7 7 5 7 7
 7 7 7 7 7 7 7 7 5 7 7 7 7 5 3 7 3 7 5 5 7 7 7 7 7 3]


In [4]:
# now we will return 2-D with 3 rows each containing 5 values:
from numpy import random
ak = random.choice([3,5,7,9], p=[0.1,0.3,0.6,0.0],size=(3,5))
print(ak)


[[7 7 7 5 7]
 [5 7 3 7 5]
 [7 5 5 7 7]]
