In [7]:
# Permutaion refers to an arrangement of elements like[3,2,1] is permutaion of [1,2,3] and vice versa.

# the numpy random module provides 2 methods: shuffle() and permutation().

# now we will randomly suffle elements for the below array:

# shuffle() method make change to the original array
from numpy import random
import numpy as np
ak = np.array([1,2,3,4,5])
random.shuffle(ak)
print(ak)

[4 2 5 3 1]


In [11]:
# now we will generate a permutation of elements for the below array:
from numpy import random
import numpy as np
ak = np.array([1,2,3,4,5])
random.permutation(ak)
print(ak)


[1 2 3 4 5]


In [14]:
# now we will generate a permutation of elements for the below array:

# The permutation() method leaves the original array unchangeed.
from numpy import random
import numpy as np
ak = np.array([1,2,3,4,5])

print(random.permutation(ak))

[1 2 5 4 3]
