In [1]:
# arithmetic operators: +,-,/,*
# by using additional aguments loke, where, dtype nad out.
# here now we will use add()

import numpy as np
ak1=np.array([1,2,3,4,5])
ak2=np.array([6,7,8,9,10])
ak3=np.add(ak1,ak2)
print(ak3)


[ 7  9 11 13 15]


In [2]:
# subdtract the value
import numpy as np
ak1=np.array([1,2,3,4,5])
ak2=np.array([6,7,8,9,10])
ak3=np.subtract(ak1,ak2)
print(ak3)

[-5 -5 -5 -5 -5]


In [3]:
# mutiplication the value
import numpy as np
ak1=np.array([1,2,3,4,5])
ak2=np.array([6,7,8,9,10])
ak3=np.multiply(ak1,ak2)
print(ak3)

[ 6 14 24 36 50]


In [4]:
# divide te value
import numpy as np
ak1=np.array([1,2,3,4,5])
ak2=np.array([6,7,8,9,10])
ak3=np.divide(ak1,ak2)
print(ak3)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [5]:
# power() function raise the value from the 1st array to the power of the values of the
# 2nd array and return the results in a new array
import numpy as np
ak1=np.array([11,12,13,14,15])
ak2=np.array([6,7,8,9,10])
ak3=np.power(ak1,ak2)
print(ak3)


[   1771561   35831808  815730721 -813789696 1124772961]


In [7]:
# reminder- mod() and reminder() function return the reminder of the 1st array 
# corrosponding to the 2nd array, and result in the new array.

import numpy as np
ak1=np.array([10,20,30,40,50])
ak2=np.array([3,7,9,8,2])
ak3=np.mod(ak1,ak2)
print(ak3)


[1 6 3 0 0]


In [10]:
# by using reminder
import numpy as np
ak1=np.array([10,20,30,40,50])
ak2=np.array([3,7,9,8,2])
ak3=np.remainder(ak1,ak2)
print(ak3)

[1 6 3 0 0]


In [11]:
# quotient and mod(remiander)
# the divmod() function return both the quotient and mod.
import numpy as np
ak1=np.array([10,20,30,40,50])
ak2=np.array([3,7,9,8,2])
ak3=np.divmod(ak1,ak2)
print(ak3)

(array([ 3,  2,  3,  5, 25]), array([1, 6, 3, 0, 0]))


In [15]:
# absolute and abs()
# - do same opertion but here we should use absolute() to avaoid confusion with 
# python inbuilt function math.abs()

import numpy as np
ak=np.array([-1,-2,-3,-4,-5,-87])
ak1 = np.absolute(ak)
print(ak1)

[ 1  2  3  4  5 87]
