summations : difference : addition is done b/w 2 argyments where summation happens 
over n elements.


In [1]:
# adding the 2 array.
import numpy as np
ak1=np.array([1,2,3])
ak2=np.array([1,2,3])
ak3=np.add(ak1,ak2)
print(ak3)

[2 4 6]


In [3]:
# sumation
import numpy as np
ak1=np.array([1,2,3])
ak2=np.array([1,2,3])
ak3=np.sum([ak1,ak2])
print(ak3)

12


In [8]:
# sumation over an axis:If you specify axis=1, NumPy will sum the numbers in each array.
import numpy as np
ak1=np.array([1,2,3])
ak2=np.array([1,2,3])
ak3=np.sum([ak1,ak2],axis=0)
ak4=np.sum([ak1,ak2],axis=1)
ak5=np.sum([ak1,ak2])
print(ak5)
print(ak3)
print(ak4)

12
[2 4 6]
[6 6]


In [10]:
# Cummulative Sum

# Cummulative sum means partially adding the elements in array.
# E.g. The partial sum of [1, 2, 3, 4] would be [1, 1+2, 1+2+3, 1+2+3+4] = [1, 3, 6, 10].
# Perfom partial sum with the cumsum() function.

import numpy as np
ak = np.array([1,2,3])
ak1 = np.cumsum(ak)
print(ak1)


[1 3 6]
