# Trignometric function : 
numpy provides the ufuns like sin(),cos() and tan() that takes value in radians and produce the corresponding sin, cos, tan values.

// here now we will find sin value of pi/2.





In [1]:
import numpy as np
ak=np.sin(np.pi/2)
print(ak)

1.0


In [4]:
# we will now find the sin value of an array

import numpy as np
ak=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
ak1=np.sin(ak)
print(ak1)

[1.         0.8660254  0.70710678 0.58778525]


In [2]:
# convert Degree into radians: by default all of the trignomertics function tales radiuns as parameter
#note: radians values are pi/180*.

# here we will convert all the array values to radians:
import numpy as np
ak= np.array([90,180,270,360])
ak1 = np.deg2rad(ak)
print(ak1)

[1.57079633 3.14159265 4.71238898 6.28318531]


In [3]:
# Here we will convert: radians into degree

import numpy as np
ak = np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
ak1=np.rad2deg(ak)
print(ak1)

[ 90. 180. 270. 360.]


# Find Angle:
arcsin(), arccos(), arctan() that takes values in radians and produc the corresing sin,cos ,tan values.

In [4]:
# we will find the angle of 1.0
import numpy as np
ak=np.arcsin(1.0)
print(ak)

1.5707963267948966


In [5]:
# angles of each values in an array:
import numpy as np
ak=np.array([1,-1,0.1])
ak1=np.arcsin(ak)
print(ak1)

[ 1.57079633 -1.57079633  0.10016742]


here we can also find the hypotenous using the pythagores theorem in numpy.
# hypot():
function that takes the base and perpendicular values and produces
hypotenues based on pythagoras theorem.

In [6]:
# here we will find the hypot for 4 base 3 perpendicular.
import numpy as np
base=3
perp=4
ak=np.hypot(base,perp)
print(ak)

5.0
