In [2]:
#slicing array- slicing in python means taking elements from one given index to another index.
#[start:end],[start:end:step]


# now we will slice sn element from 1 to 5 :

import numpy as np
ak = np.array([1,2,3,4,5,6,7,8,9])
print(ak[1:5])

[2 3 4 5]


In [3]:
# now we will slicefrom index 4 to end value:
import numpy as np
ak= np.array([1,2,3,4,5,6,7,8,9])
print(ak[4:])

[5 6 7 8 9]


In [4]:
# now we will slice the element from the begining to index 4
import numpy as np
ak= np.array([1,2,3,4,5,6,7,8,9])
print(ak[:4])

[1 2 3 4]


In [7]:
# negative slicing
# inex 3 to end
import numpy as np
ak= np.array([1,2,3,4,5,6,7,8,9])
print(ak[-6:-1])
print(ak[3:-1])

[4 5 6 7 8]
[4 5 6 7 8]


In [12]:
# step you will use step value to determine the step of the slicing
# return every other value from 1 to 5
import numpy as np
ak= np.array([1,2,3,4,5,6,7,8,9])
print(ak[1:5])
print(ak[1:5:2])
# now return every other number from the entire array
print(ak[::2])

[2 3 4 5]
[2 4]
[1 3 5 7 9]


In [14]:
# skicing 2_D Array print 7,8,9
import numpy as np 
ak =np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ak[1,1:4])

[7 8 9]


In [15]:
# another example
import numpy as np
ak= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ak[0:2,2])


[3 8]


In [16]:
# another example tough 2-D - print from both, index 1:4
import numpy as np
ak= np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(ak[0:2,1:4])

[[2 3 4]
 [7 8 9]]
