In [4]:
#difference between numpy array copy and view
# we will makw the copy,change in origenal array, and display both.
import numpy as np
ak=np.array([1,2,3,4,5])
ak1=ak.copy()
ak1[0]=42
print(ak)
print(ak1)

[1 2 3 4 5]
[42  2  3  4  5]


In [3]:
#Now wewill make a view, change original,display both
import numpy as np
ak=np.array([1,2,3,4,5])
ak1=ak.view()
ak[0]=42
print(ak)
print(ak1)


[42  2  3  4  5]
[42  2  3  4  5]
