In [4]:
#re-shaping the shape of an array,like adding or removing the elements.

#re-shaping from 1-D to 2-D

import numpy as np
ak = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ak1= ak.reshape(4,3)
print(ak1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
# re-shaping from 1-D to 3-D
import numpy as np
ak = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
ak1= ak.reshape(2,3,2)
print(ak1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [9]:
import numpy as np
ak = np.array([1,2,3,4,5,6,7,8])
# ak1= ak.reshape(3,3)
ak1= (ak.reshape(2,4).base)
print(ak1)

[1 2 3 4 5 6 7 8]


In [11]:
# unknow dimension - you are only allowed to have one unknow dimension.pass -1.
import numpy as np
ak = np.array([1,2,3,4,5,6,7,8])
ak1= ak.reshape(2,2,-1)
print(ak1)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [13]:
#Flattening the array by converting multidimensional array in 1-D
import numpy as np
ak=np.array([[1,2,3],[4,5,6]])
ak1=ak.reshape(-1)
print(ak1)

# there are alot of function for changing the shapes of an in array in nupy.
# like flatten, ravel and also rearranging  the element rot90,flip,flipir,flipud.
#they all are actually comes under advanced numpy.

[1 2 3 4 5 6]
