What is a Set
A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.



We can use NumPy's unique() method to find unique elements from any array. E.g. create a set array, but remember that the set arrays should only be 1-D arrays.

In [1]:
# Convert following array with repeated elements to a set:
import numpy as np
ak=np.array([1,1,1,2,3,4,5,5,6,7])
ak1=np.unique(ak)
print(ak1)

[1 2 3 4 5 6 7]


In [3]:
# to find the unique values of 2 D array,we will use union1D() method.
import numpy as np
ak=np.array([1,2,3,4])
ak1=np.array([3,4,5,6])
ak2=np.union1d(ak,ak1)
print(ak2)

[1 2 3 4 5 6]



# Finding Intersection
To find only the values that are present in both arrays, use the intersect1d() method.

In [4]:
import numpy as np

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

newarr = np.intersect1d(arr1, arr2, assume_unique=True)

print(newarr)

[3 4]


 # Finding Difference
To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

In [5]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setdiff1d(set1, set2, assume_unique=True)

print(newarr)

[1 2]


# Finding Symmetric Difference
To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

In [6]:
import numpy as np

set1 = np.array([1, 2, 3, 4])
set2 = np.array([3, 4, 5, 6])

newarr = np.setxor1d(set1, set2, assume_unique=True)

print(newarr)

[1 2 5 6]
